spring:
  application:
    name: 73NP0-7L
  cache:
    cache-names: percentage
    caffeine:
      spec: expireAfterWrite=30m
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5332/DESAFIO_TENPO}
    username: ${SPRING_DATASOURCE_USERNAME:desafio_tenpo}
    password: ${SPRING_DATASOURCE_PASSWORD:d3s4f10t3np0}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

logging:
  level:
    root: INFO

app:
  client:
    percentage:
      url: http://localhost:8080
      mock:
        enabled: true
  interceptor:
    rateLimiting:
      rpm: 3 #request por minuto
